"""Setup utilities for SPAM environment configuration"""

import getpass
import os
from pathlib import Path

from utils.logging_config import get_logger
from utils.exceptions import ConfigurationError


logger = get_logger(__name__)


def setup_environment() -> None:
    """Interactive setup for SPAM environment variables"""
    print("SPAM Environment Setup")
    print("=" * 50)
    
    # Get environment file path
    env_file = Path('.env')
    
    if env_file.exists():
        overwrite = input(f"{env_file} already exists. Overwrite? (y/N): ")
        if overwrite.lower() not in ['y', 'yes']:
            print("Setup cancelled.")
            return
    
    # Collect environment variables
    env_vars = {}
    
    print("\nProxmox Configuration:")
    env_vars['PROXMOX_HOST'] = input("Proxmox host/IP: ").strip()
    env_vars['PROXMOX_USER'] = input("Proxmox username: ").strip()
    env_vars['PROXMOX_PASSWORD'] = getpass.getpass("Proxmox password: ").strip()
    env_vars['PROXMOX_REALM'] = input("Proxmox realm (default: pve): ").strip() or 'pve'
    env_vars['PROXMOX_DEFAULT_NODE'] = input("Default Proxmox node (optional): ").strip()
    
    print("\nSPAM Configuration:")
    env_vars['CONFIG_PATH'] = input("Default config file path (default: conf/env.yaml): ").strip() or 'conf/env.yaml'
    env_vars['SPAM_LOG_LEVEL'] = input("Log level (default: INFO): ").strip() or 'INFO'
    
    # Validate required fields
    required_fields = ['PROXMOX_HOST', 'PROXMOX_USER', 'PROXMOX_PASSWORD']
    for field in required_fields:
        if not env_vars[field]:
            raise ConfigurationError(f"Required field {field} cannot be empty")
    
    # Write .env file
    try:
        with open(env_file, 'w') as f:
            f.write("# SPAM Environment Configuration\n")
            f.write("# Generated by SPAM setup\n\n")
            
            for key, value in env_vars.items():
                if value:  # Only write non-empty values
                    f.write(f"{key}={value}\n")
        
        print(f"\nEnvironment configuration saved to {env_file}")
        print("Setup completed successfully!")
        
    except OSError as e:
        raise ConfigurationError(f"Could not write environment file: {e}")


def validate_environment() -> bool:
    """Validate that required environment variables are set"""
    required_vars = ['PROXMOX_HOST', 'PROXMOX_USER', 'PROXMOX_PASSWORD', 'PROXMOX_REALM']
    
    missing_vars = []
    for var in required_vars:
        if not os.getenv(var):
            missing_vars.append(var)
    
    if missing_vars:
        logger.error(f"Missing required environment variables: {', '.join(missing_vars)}")
        logger.info("Run 'spam setup' to configure your environment")
        return False
    
    return True


def get_proxmox_config() -> dict:
    """Get Proxmox configuration from environment variables"""
    if not validate_environment():
        raise ConfigurationError("Environment not properly configured")
    
    return {
        'host': os.getenv('PROXMOX_HOST'),
        'user': os.getenv('PROXMOX_USER'),
        'password': os.getenv('PROXMOX_PASSWORD'),
        'realm': os.getenv('PROXMOX_REALM', 'pve'),
        'default_node': os.getenv('PROXMOX_DEFAULT_NODE')
    }