env:
  template_node: cuci-r730-pve03
  nodes:
    - cuci-r730-pve02
    - cuci-r730-pve03
  copies: 4
  vmid_start: 1333338
  router_ip: 10.121.X.0/8
  gw: 10.0.0.1
  bridge_start: 10
  boxes:
  - id: '20250503'
    config:
      name: witch
    cloud:
  - id: '20250502'
    config:
      name: enderman
    cloud:
  - id: '20250501'
    config:
      name: ocelot
    cloud:
